src/Entity/Video.php
<?php

namespace App\Entity;

use App\Repository\VideoRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VideoRepository::class)]
class Video
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $duration = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $release_date = null;

    #[ORM\Column(length: 50)]
    private ?string $type = null;

    #[ORM\Column(length: 255)]
    private ?string $link = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDuration(): ?string
    {
        return $this->duration;
    }

    public function setDuration(?string $duration): static
    {
        $this->duration = $duration;

        return $this;
    }

    public function getReleaseDate(): ?\DateTimeInterface
    {
        return $this->release_date;
    }

    public function setReleaseDate(?\DateTimeInterface $release_date): static
    {
        $this->release_date = $release_date;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(string $link): static
    {
        $this->link = $link;

        return $this;
    }
}

src/Form/VideoType.php
<?php

namespace App\Form;

use App\Entity\Video;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VideoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('duration')
            ->add('release_date')
            ->add('link')
            ->add('type', ChoiceType::class, [
                'choices' => [
                    'premium' => 'premium',
                    'free' => 'free'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Video::class,
        ]);
    }
}

src/Controller/VideoController.php
<?php

namespace App\Controller;

use App\Entity\Video;
use App\Form\VideoType;
use App\Repository\VideoRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/video')]
class VideoController extends AbstractController
{
    #[Route('/', name: 'app_video_index', methods: ['GET'])]
    public function index(VideoRepository $videoRepository): Response
    {
        return $this->render('video/index.html.twig', [
            'videos' => $videoRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_video_new', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_ADMIN')]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $video = new Video();
        $form = $this->createForm(VideoType::class, $video);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($video);
            $entityManager->flush();

            return $this->redirectToRoute('app_video_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('video/new.html.twig', [
            'video' => $video,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'app_video_show', methods: ['GET'])]
    public function show(Video $video): Response
    {
        if ($video->getType() === "premium" && $this->isGranted("ROLE_PREMIUM") || $video->getType() === "free" && $this->isGranted("ROLE_FREE")) {
            return $this->render('video/show.html.twig', [
                'video' => $video,
            ]);
        }
        return $this->redirectToRoute('app_home');

    }

    #[Route('/{id}/edit', name: 'app_video_edit', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_ADMIN')]
    public function edit(Request $request, Video $video, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(VideoType::class, $video);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_video_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('video/edit.html.twig', [
            'video' => $video,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'app_video_delete', methods: ['POST'])]
    #[IsGranted('ROLE_ADMIN')]
    public function delete(Request $request, Video $video, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$video->getId(), $request->request->get('_token'))) {
            $entityManager->remove($video);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_video_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/video/_delete_form.html.twig
<form method="post" action="{{ path('app_video_delete', {'id': video.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ video.id) }}">
    <button class="btn">Delete</button>
</form>

templates/video/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/video/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Video{% endblock %}

{% block body %}
    <h1>Edit Video</h1>

    {{ include('video/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_video_index') }}">back to list</a>

    {{ include('video/_delete_form.html.twig') }}
{% endblock %}

templates/video/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Video index{% endblock %}

{% block body %}
    <h1>Video index</h1>
        {% for video in videos %}
            <a href="{{ path('app_video_show', {'id' : video.id}) }}">
                <p>{{ video.duration }}</p>
                <p>{{ video.releaseDate ? video.releaseDate|date('Y-m-d') : '' }}</p>
                <p>
                    <a href="{{ path('app_video_show', {'id': video.id}) }}">show</a>
                    <a href="{{ path('app_video_edit', {'id': video.id}) }}">edit</a>
                </p>
            </a>
        {% else %}
                <p>no records found</p>
        {% endfor %}

    {% if is_granted("ROLE_ADMIN") %}
        <a href="{{ path('app_video_new') }}">Create new</a>
    {% endif %}
{% endblock %}

templates/video/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Video{% endblock %}

{% block body %}
    <h1>Create new Video</h1>

    {{ include('video/_form.html.twig') }}

    <a href="{{ path('app_video_index') }}">back to list</a>
{% endblock %}

templates/video/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Video{% endblock %}

{% block body %}
    <h1>Video</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ video.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ video.title }}</td>
            </tr>
            <tr>
                <th>Duration</th>
                <td>{{ video.duration }}</td>
            </tr>
            <tr>
                <th>Release_date</th>
                <td>{{ video.releaseDate ? video.releaseDate|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>
    <iframe width="2560" height="1112" src="{{ video.link }}" title="{{  video.title }}" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>                <p>{{ video.title }}</p>


    <a href="{{ path('app_video_index') }}">back to list</a>

    <a href="{{ path('app_video_edit', {'id': video.id}) }}">edit</a>

    {{ include('video/_delete_form.html.twig') }}
{% endblock %}